### ISSUE TITLE
with RelativeLayouts is not working

### ISSUE THREAD

**Issue by hvar90** [hluhovskyi/HoldingButton#1]
i wanna use Relative layouts instead linear layout because i wanna use   android:layout_alignParentBottom="true" because i wanna to have fixed the input box and the buttons at the  #bottom. but when i change the linear layout with relative layout it is broken

>     <com.dewarder.holdinglibrary.HoldingButtonLayout
>     android:id="@+id/input_holder"
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content"
>     android:layout_alignParentBottom="true"
>     android:layout_centerHorizontal="true"
>     app:hbl_cancel_icon="@drawable/ic_close_black_24dp"
>     app:hbl_holding_view="@+id/start_record"
>     app:hbl_icon="@drawable/ic_mic_white_24dp"
>     app:hbl_radius="@dimen/activity_main_holding_button_radius"
>     app:hbl_second_radius="@dimen/activity_main_holding_button_second_radius">
>     <RelativeLayout
>         android:id="@+id/slide_to_cancel"
>         android:layout_width="match_parent"
>         android:layout_height="40dp"
>         android:minHeight="40dp"> 
>         android:background="@android:color/white"
>         android:layout_alignParentBottom="true"
>         android:visibility="invisible">
>         <TextView
>             android:id="@+id/time"
>             android:layout_width="wrap_content"
>             android:layout_height="wrap_content"
>             android:layout_alignParentLeft="true"
>             android:layout_alignParentBottom="true"
>             android:text="00:00:00"
>             android:textSize="25dp"
>             />
>         <TextView
>             android:id="@+id/textView_to_cancel"
>             android:layout_width="wrap_content"
>             android:layout_height="wrap_content"
>             android:layout_alignParentRight="true"
>             android:layout_alignParentBottom="true"
>             android:text="@string/label_slide_to_cancel"/>
>         <ImageView
>             android:layout_width="@dimen/activity_main_slide_to_cancel_icon_size"
>             android:layout_height="@dimen/activity_main_slide_to_cancel_icon_size"
>             android:layout_marginEnd="@dimen/activity_main_slide_to_cancel_icon_margin_right"
>             android:layout_marginRight="@dimen/activity_main_slide_to_cancel_icon_margin_right"
>             android:scaleType="center"
>             android:layout_toRightOf="@id/time"
>             android:layout_toLeftOf="@id/textView_to_cancel"
>             android:layout_alignParentBottom="true"
>             android:src="@drawable/ic_keyboard_arrow_left_black_24dp"/>
>     </RelativeLayout>
>     <RelativeLayout
>         android:id="@+id/box_emoji_input_text"
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:minHeight="40dp">
> 
>         <ImageView
>             android:id="@+id/emoji_btn"
>             android:layout_width="wrap_content"
>             android:layout_height="wrap_content"
>             android:layout_alignParentBottom="true"
>             android:background="@android:color/white"
>             android:layout_alignParentLeft="true"
>             android:minHeight="40dp"
>             android:src="@drawable/smiley"
>             />
> 
>         <ImageView
>             android:id="@+id/submit_btn"
>             android:layout_alignParentBottom="true"
>             android:layout_marginRight="@dimen/input_margin_right"
>             android:background="@android:color/white"
>             android:layout_height="wrap_content"
>             android:layout_width="wrap_content"
>             android:minHeight="40dp"
>             android:layout_toLeftOf="@id/start_record"
>             android:src="@drawable/ic_action_send_now"
>             />
>         <com.vanniktech.emoji.EmojiEditText
>             android:id="@+id/emojicon_edit_text"
>             android:layout_alignParentBottom="true"
>             android:paddingBottom="@dimen/activity_main_input_padding_vertical"
>             android:paddingTop="@dimen/activity_main_input_padding_vertical"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             android:hint="@string/typeMessage"
>             android:textColorHint="#bcbcbc"
>             android:inputType="textCapSentences|textAutoCorrect|textMultiLine"
>             android:minHeight="40dp"
>             android:background="@android:color/white"
>             android:layout_toRightOf="@id/emoji_btn"
>             android:layout_toLeftOf="@id/submit_btn"
>             emojicon:emojiSize="26dp" />
>         <ImageView
>             android:id="@+id/start_record"
>             android:layout_alignParentBottom="true"
>             android:layout_width="@dimen/activity_main_start_record_width"
>             android:layout_height="@dimen/activity_main_start_record_height"
>             android:scaleType="center"
>             android:background="@drawable/round_image"
>             android:layout_alignParentRight="true"
>             android:src="@drawable/ic_mic_white_24dp"/>
> 
>         <ListView
>             android:id="@+id/lv"
>             android:listSelector="@android:color/transparent"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent"
>             android:layout_above="@id/emojicon_edit_text"
>             android:layout_alignParentLeft="false"
>             android:layout_alignParentTop="false"
>             android:transcriptMode="normal"
>             android:layout_marginBottom="5dp"
>             android:paddingBottom="5dp"
>             android:divider="@null"
>             />
>     </RelativeLayout>
> 
>     </com.dewarder.holdinglibrary.HoldingButtonLayout>

**Comment by hvar90** [comment]
i fixed my problem using linear layout and  android:layout_gravity="bottom|center_horizontal"

**Comment by hluhovskyi** [comment]
Hello. You should wrap with `HoldingButtonLayout` only your bottom panel with input and then position it inside `RelativeLayout` as solid block.
