### ISSUE TITLE
How to disable HoldingButton.

### ISSUE THREAD

**Issue by tuhin10** [hluhovskyi/HoldingButton#3]
I want to disable Holding Button on certain conditions from the activity,

**Comment by hluhovskyi** [comment]
Hello. There is no easy way to do this, because it wasn't implemented. So I will try to do it as soon as possible and will publish new version after that.

**Comment by hluhovskyi** [comment]
Implemented at 0.0.7. Just update your dependency version and call `setButtonEnabled` from Java code or add `hbl_enabled` to xml.

**Comment by tuhin10** [comment]
thanks a lot
